# Generated by Django 3.2.7 on 2022-06-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='data', verbose_name='Datei'),
        ),
    ]
