# Generated by Django 3.2.7 on 2022-06-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_images_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Datei'),
        ),
    ]
