# Generated by Django 4.0.5 on 2022-11-15 15:51

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer_head_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='head_2',
            field=models.FileField(blank=True, null=True, storage=app.models.PDFStorage(), upload_to=app.models.get_upload_path),
        ),
    ]
