# Generated by Django 4.0.5 on 2022-11-18 18:31

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer_head_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='head_3',
            field=models.FileField(blank=True, null=True, storage=app.models.PDFStorage(), upload_to=app.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='customer',
            name='head_4',
            field=models.FileField(blank=True, null=True, storage=app.models.PDFStorage(), upload_to=app.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='customer',
            name='head_5',
            field=models.FileField(blank=True, null=True, storage=app.models.PDFStorage(), upload_to=app.models.get_upload_path),
        ),
    ]
