# Generated by Django 3.2.7 on 2022-06-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_images_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='displayed',
            field=models.BooleanField(default=False),
        ),
    ]
