# Generated by Django 3.2.7 on 2022-06-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_images_displayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
