# Generated by Django 4.0.5 on 2022-11-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_images_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=30)),
                ('offer_pdf', models.FileField(blank=True, null=True, upload_to='')),
                ('extra_pdf', models.FileField(blank=True, null=True, upload_to='')),
                ('success', models.BooleanField(default=False)),
            ],
        ),
    ]
