# Generated by Django 4.0.5 on 2022-11-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_images_customer_date_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardPDFs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
