# Generated by Django 4.0.5 on 2022-11-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_standardpdfs'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='StandardPDFs',
        ),
    ]
