# Generated by Django 4.0.5 on 2022-11-05 19:14

import app.models
from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_customer_extra_pdf_customer_offer_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='anrede',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='hausnr',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='iban',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=50, null=True)),
        ),
        migrations.AddField(
            model_name='customer',
            name='nachname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='ort',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='plz',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='strasse',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='vorname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='client_id',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='standardpdf',
            name='pdf',
            field=models.FileField(blank=True, null=True, storage=app.models.StandardPDFStorage(), upload_to=app.models.get_standard_upload_path),
        ),
    ]
