# Generated by Django 4.0.5 on 2022-11-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_customer_birthdate_alter_customer_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='iban',
            field=models.BinaryField(default=b'\x08'),
        ),
    ]
