# Generated by Django 3.2.7 on 2021-12-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termine',
            name='datum',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Termindatum'),
        ),
    ]
