# Generated by Django 3.2.7 on 2021-12-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211212_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Kommentar'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='produkt',
        ),
        migrations.AddField(
            model_name='order',
            name='produkt',
            field=models.ManyToManyField(blank=True, null=True, to='app.Product'),
        ),
    ]
