# Generated by Django 3.2.7 on 2021-12-12 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211212_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='produkt',
        ),
        migrations.AddField(
            model_name='order',
            name='produkt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
