# Generated by Django 3.2.7 on 2022-03-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20211216_1633'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CRM',
        ),
        migrations.DeleteModel(
            name='Kommunikationstool',
        ),
        migrations.RemoveField(
            model_name='order',
            name='kunde',
        ),
        migrations.RemoveField(
            model_name='order',
            name='produkt',
        ),
        migrations.RemoveField(
            model_name='signale',
            name='kunde',
        ),
        migrations.RemoveField(
            model_name='signale',
            name='produkt',
        ),
        migrations.RemoveField(
            model_name='termine',
            name='kunde',
        ),
        migrations.RemoveField(
            model_name='termine',
            name='produkt',
        ),
        migrations.DeleteModel(
            name='Warenwirtschaftssystem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Signale',
        ),
        migrations.DeleteModel(
            name='Termine',
        ),
    ]
