# Generated by Django 3.2.7 on 2022-03-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20220306_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Firmenname')),
                ('website', models.CharField(blank=True, max_length=50, null=True, verbose_name='Firmenwebseite')),
                ('comment', models.TextField(blank=True, max_length=1000, verbose_name='Kommentar')),
            ],
            options={
                'verbose_name': 'Kunde',
                'verbose_name_plural': 'Kunden',
            },
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
