# Generated by Django 3.2.7 on 2022-03-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20220306_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterField(
            model_name='images',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='images',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Filename'),
        ),
        migrations.AlterField(
            model_name='images',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Website'),
        ),
    ]
